# generated by datamodel-codegen:
#   filename:  case.schema.json

from __future__ import annotations
from typing import Any, Literal
from pydantic import BaseModel, ConfigDict, Field


class DenyMessage(BaseModel):
    """
    The explicit form of a [`DenySpec`]: the model-visible message.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    message: str


class BooleanEval(BaseModel):
    """
    Assert a plain-English criterion holds (or, with `expected: false`, that
    it does not).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    criterion: str = Field(
        ..., description="The criterion the judge evaluates against the transcript."
    )
    expected: bool | None = Field(
        True, description="What the judge's verdict must equal to pass. Defaults to `true`."
    )
    name: str | None = Field(None, description="Optional human label for reports.")
    type: Literal["boolean"]


class NumericEval(BaseModel):
    """
    Score a plain-English criterion on a numeric scale and compare it to a
    threshold.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    comparator: Literal["gte", "gt", "lte", "lt"] | None = Field(
        "gte", description="How the score is compared to `threshold`. Defaults to `>=`."
    )
    criterion: str = Field(..., description="The criterion the judge scores.")
    max: float = Field(..., description="Inclusive upper bound of the scale.")
    min: float = Field(..., description="Inclusive lower bound of the scale.")
    name: str | None = Field(None, description="Optional human label for reports.")
    threshold: float = Field(..., description="The passing threshold.")
    type: Literal["numeric"]


class FieldPredicateSpec(BaseModel):
    """
    The explicit form of a [`FieldPredicate`]; every given key must hold.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contains: str | None = None
    equals: str | None = None
    pattern: str | None = Field(
        None, description="Unanchored regex (linear-time; same engine oneharness uses)."
    )


class SimulatedUser(BaseModel):
    """
    The simulated-user block that turns a single-turn case into a multi-turn one.
    When present, after each assistant turn the runner asks the provider to play
    the user (guided by `persona`) until `done_when` holds or `max_turns` is hit.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    done_when: str | None = Field(
        None,
        description="A plain-English condition; when the judge decides it holds, the\nconversation ends. Optional — without it the run ends at `max_turns` or\nwhen the skill reports itself done.",
    )
    max_turns: int | None = Field(
        None, description="Per-case override of the global assistant-turn cap.", ge=0
    )
    persona: str = Field(
        ..., description="Instructions describing how the simulated user should behave."
    )


class StubOutput(BaseModel):
    """
    The explicit form of a [`StubSpec`]: the canned output plus an exit code.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    exit_code: int | None = Field(0, description="Non-zero fakes a failing command. Default 0.")
    output: str


class MockMatch(BaseModel):
    """
    What a mock/spy declaration matches on. At least one criterion is required;
    every given criterion must hold (AND).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contains: str | None = Field(
        None,
        description="Substring match over the raw hook event JSON (the tool name and its\ninput always serialize into it). Note the haystack is JSON: quotes and\nbackslashes inside tool input appear escaped.",
    )
    input: dict[str, str | FieldPredicateSpec] | None = Field(
        None,
        description="Per-field predicates on the tool's input: the key is the argument name\n(`command`, `file_path`, …), and every listed field must match (a field\nabsent from the call fails the matcher). Non-string fields are compared\nagainst their compact JSON form.",
    )
    pattern: str | None = Field(
        None,
        description="Unanchored regex over the same haystack as `contains`, for non-exact\nneedles like `git push( --force)?`. Linear-time engine (no lookarounds).",
    )
    tool: str | None = Field(
        None,
        description="Case-insensitive exact match on the tool name. Tool names are\nper-harness (`Bash` on claude-code, `bash` on opencode/crush), so\ncross-harness matchers usually prefer `contains`/`pattern`/`input`.",
    )


class CalledEval(BaseModel):
    """
    Deterministic: assert the referenced mock/spy observed at least one
    matching call (or exactly `times`). Evaluated against the mock channel's
    records, not by a judge.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mock: str = Field(
        ..., description="The `mocks:` declaration (mock or spy) this asserts on, by name."
    )
    name: str | None = Field(None, description="Optional human label for reports.")
    times: int | None = Field(
        None, description='Exact required call count; absent means "at least once".', ge=0
    )
    type: Literal["called"]
    where: dict[str, str | FieldPredicateSpec] | None = Field(
        None, description="Optional per-field input predicates narrowing which calls count."
    )


class NotCalledEval(BaseModel):
    """
    Deterministic: assert the referenced mock/spy observed **no** matching
    call.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mock: str = Field(
        ..., description="The `mocks:` declaration (mock or spy) this asserts on, by name."
    )
    name: str | None = Field(None, description="Optional human label for reports.")
    type: Literal["not_called"]
    where: dict[str, str | FieldPredicateSpec] | None = Field(
        None, description="Optional per-field input predicates narrowing which calls count."
    )


class MockDecl(BaseModel):
    """
    One mock or spy declaration — an entry of a test case's `mocks:` block, of
    the CLI's `--mocks` file, or synthesized by an SDK. Exactly one of `stub` /
    `deny` / `rewrite` makes it a **mock** (the call is intercepted); none makes
    it a **spy** (observed only, matched locally against the returned records).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    deny: str | DenyMessage | None = Field(
        None, description="Block the call; the model reads the message as the tool's feedback."
    )
    match: MockMatch
    name: str | None = Field(
        None,
        description="Name evals (`type: called` / `not_called`) reference this declaration\nby. Optional; unnamed declarations get a positional fallback\n(`mock_<i>` / `spy_<i>`) used in reports and error messages.",
    )
    rewrite: Any | None = Field(
        None,
        description="Substitute raw input fields (a JSON object) — the low-level escape\nhatch, and the way to mock file reads (rewrite `file_path` to a\nfixture).",
    )
    stub: str | StubOutput | None = Field(
        None,
        description="Fake a shell call's result: the real command never runs and the model\nreceives this output as the tool's genuine result.",
    )


class TestCase(BaseModel):
    """
    One test case.

    This type is the source of truth for the **input contract**
    (`schemas/case.schema.json`): the shape a `--case-json` payload — and the
    SDKs' generated case models — must have. Serialization skips
    absent/default fields so the canonical JSON form is minimal; the SDK case
    builders emit that same form (pinned by the kitchen-sink golden in
    `tests/fixtures/contract/`).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    evals: list[BooleanEval | NumericEval | CalledEval | NotCalledEval] = Field(
        ..., description="The evals that decide whether this case passes. Must be non-empty."
    )
    input: str = Field(
        ..., description="The initial data/prompt handed to the skill as the first user message."
    )
    mocks: list[MockDecl] | None = Field(
        None,
        description="Mock/spy declarations for this case: a declaration with a `stub`/`deny`/\n`rewrite` action intercepts matching tool calls; one without observes\nonly. `called`/`not_called` evals reference these by `name`.",
    )
    name: str | None = Field(
        None, description="Human-readable name (defaults to the file stem when loaded from a file)."
    )
    skill: str = Field(
        ..., description="Path to the skill directory under test, relative to the test-case file."
    )
    spy: bool | None = Field(
        None,
        description="Record every tool call through the mock/spy channel even with no\n`mocks` declared, so code-level consumers (the SDKs' spies) get records.\nImplied whenever `mocks` is non-empty.",
    )
    user: SimulatedUser | None = Field(
        None, description="Present for multi-turn cases; absent for single-turn."
    )
