# generated by datamodel-codegen:
#   filename:  error.schema.json

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, Field


class ReportError(BaseModel):
    """
    A structured error, emitted as the `--format json` / `json-stream` output
    when a `skilltest run` cannot produce a [`Report`].

    This is the machine-readable counterpart to the human hint the CLI prints on
    stderr: it rides on stdout so SDK/plugin consumers get the [`ProviderErrorKind`]
    (and the `code`/`context`) for targeted handling — retry on
    [`ProviderErrorKind::Timeout`], fail fast on [`ProviderErrorKind::Auth`] —
    instead of matching substrings in the message. For `json` the object is
    emitted bare; for `json-stream` it is the terminal
    `{"type":"error","error":{…}}` line.
    """

    code: Literal["usage", "provider"] = Field(
        ..., description="The coarse failure class, matching the process exit code."
    )
    context: str | None = Field(
        None,
        description="The provider context the failure came from (e.g. `oneharness:claude-code`,\n`api-judge`). Absent for usage errors.",
    )
    kind: (
        Literal[
            "auth",
            "rate_limit",
            "model_not_found",
            "quota",
            "overloaded",
            "timeout",
            "spawn",
            "protocol",
            "other",
        ]
        | None
    ) = Field(
        None,
        description="The structured provider-failure category, when skilltest could classify\nit. Absent for usage errors and for unclassified provider failures.",
    )
    message: str = Field(
        ...,
        description="A human-readable description of what went wrong (the same text printed on\nstderr, minus the suggested-action hint).",
    )
