# generated by datamodel-codegen:
#   filename:  report.schema.json

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, Field


class BooleanDetail(BaseModel):
    """
    The kind-specific detail of an eval outcome, for reporting.

    The variant titles name the generated SDK model for each union arm, so keep
    them stable: they are part of the SDK API surface.
    """

    expected: bool
    kind: Literal["boolean"]
    value: bool


class NumericDetail(BaseModel):
    """
    The kind-specific detail of an eval outcome, for reporting.

    The variant titles name the generated SDK model for each union arm, so keep
    them stable: they are part of the SDK API surface.
    """

    comparator: Literal["gte", "gt", "lte", "lt"] = Field(
        ..., description="How a numeric score is compared to its threshold."
    )
    kind: Literal["numeric"]
    threshold: float
    value: float


class EvalOutcome(BaseModel):
    """
    The result of running one eval against a transcript.
    """

    detail: BooleanDetail | NumericDetail = Field(..., description="Kind-specific verdict detail.")
    label: str = Field(..., description="The eval's label (name or criterion).")
    passed: bool = Field(..., description="Whether the eval passed.")
    reason: str = Field(..., description="The judge's stated reason.")


class Usage(BaseModel):
    """
    Token / cost usage for one provider call.

    Each field is independently optional because not every harness reports every
    signal (cost is commonly absent on subscription auth; some harnesses report
    no usage at all). The whole struct is `Option<Usage>` on a turn — `None`
    means "no signal," not "zero."
    """

    cost_usd: float | None = None
    input_tokens: int | None = Field(None, ge=0)
    output_tokens: int | None = Field(None, ge=0)


class Message(BaseModel):
    """
    A single turn in the conversation.
    """

    content: str
    role: Literal["user", "assistant", "system"] = Field(..., description="Who produced a message.")


class Summary(BaseModel):
    """
    Aggregate pass/fail counts for a report.
    """

    cases: int = Field(..., description="Distinct test cases represented.", ge=0)
    failed: int = Field(..., description="Runs that failed.", ge=0)
    passed: int = Field(..., description="Runs that passed.", ge=0)
    runs: int = Field(..., description="Total (case × platform × model) runs.", ge=0)
    usage: Usage | None = Field(
        None,
        description="Aggregated token/cost usage across every run in the report. Omitted\nwhen no run reported usage.",
    )


class Transcript(BaseModel):
    """
    An ordered list of messages. Thin wrapper so the type reads clearly at call
    sites and so we can grow conversation-level helpers without churn.
    """

    messages: list[Message]


class CaseRun(BaseModel):
    """
    The result of running one test case on one (platform, model) pair.
    """

    case: str = Field(..., description="The test case name.")
    evals: list[EvalOutcome] = Field(..., description="Per-eval outcomes, in declaration order.")
    model: str = Field(..., description="The model this run used.")
    passed: bool = Field(..., description="True iff every eval in this run passed.")
    platform: str = Field(..., description="The harness platform this run used.")
    skill: str = Field(..., description="Absolute-ish path to the skill that was exercised.")
    transcript: Transcript = Field(
        ..., description="The full conversation, for debugging and deterministic mix-in checks."
    )
    turns: int = Field(..., description="Number of assistant turns produced.", ge=0)
    usage: Usage | None = Field(
        None,
        description="Aggregated token/cost usage across every provider call in this run\n(skill turns + simulated-user turns + judge calls). Omitted when no\nusage was reported (e.g. the fake provider or a harness that doesn't\nsurface usage).",
    )


class Report(BaseModel):
    """
    The top-level report for a `skilltest run` invocation.
    """

    passed: bool = Field(..., description="True iff every run passed.")
    runs: list[CaseRun] = Field(..., description="Every individual run.")
    summary: Summary = Field(..., description="Aggregate counts.")
