# generated by datamodel-codegen:
#   filename:  report.schema.json

from __future__ import annotations
from typing import Any, Literal
from pydantic import BaseModel, Field


class BooleanDetail(BaseModel):
    """
    The kind-specific detail of an eval outcome, for reporting.

    The variant titles name the generated SDK model for each union arm, so keep
    them stable: they are part of the SDK API surface.
    """

    expected: bool
    kind: Literal["boolean"]
    value: bool


class NumericDetail(BaseModel):
    """
    The kind-specific detail of an eval outcome, for reporting.

    The variant titles name the generated SDK model for each union arm, so keep
    them stable: they are part of the SDK API surface.
    """

    comparator: Literal["gte", "gt", "lte", "lt"] = Field(
        ..., description="How a numeric score is compared to its threshold."
    )
    kind: Literal["numeric"]
    threshold: float
    value: float


class CallsDetail(BaseModel):
    """
    The deterministic `called`/`not_called` verdict: how many observed calls
    matched, against what expectation.
    """

    count: int = Field(..., description="Matching calls observed.", ge=0)
    kind: Literal["calls"]
    negated: bool | None = Field(
        False, description="True for `not_called` (the eval required absence)."
    )
    times: int | None = Field(
        None,
        description='The exact count required (`times`); `null` means "at least one"\n(or, with `negated`, "none").',
        ge=0,
    )


class EvalOutcome(BaseModel):
    """
    The result of running one eval against a transcript.
    """

    detail: BooleanDetail | NumericDetail | CallsDetail = Field(
        ..., description="Kind-specific verdict detail."
    )
    label: str = Field(..., description="The eval's label (name or criterion).")
    passed: bool = Field(..., description="Whether the eval passed.")
    reason: str = Field(..., description="The judge's stated reason.")


class MockCall(BaseModel):
    """
    One observed tool call, as recorded by the mock/spy channel: the harness
    hook's spy log for real runs, or the provider's `mock_calls` response for
    the command protocol. Carries the **original, pre-rewrite** input — the
    transcript's `events` show post-rewrite reality (the stub that actually
    ran); this shows what the skill *attempted*.
    """

    action: str = Field(
        ...,
        description="The verdict applied: `allow` (fell through every rule), `deny`,\n`rewrite`, or `stub`.",
    )
    input: Any | None = Field(
        None, description="The tool's original input arguments; `null` when the event carried none."
    )
    mock: str | None = Field(
        None,
        description="Name of the mock declaration the intercepting rule came from; `null`\nfor `allow`. Filled by the runner, so SDKs bind records to mock objects\nby name instead of re-deriving rule indices.",
    )
    rule: int | None = Field(
        None, description="Index of the compiled rule that intercepted; `null` for `allow`.", ge=0
    )
    tool: str | None = Field(
        None, description="Tool name as the harness reported it; `null` when the event named none."
    )


class ToolEvent(BaseModel):
    """
    One normalized tool-call / action event the skill took during a turn, lifted
    from oneharness's `events` array (its `--events` output). Harness-agnostic, so
    a consumer can inspect *what the skill did* — shell commands, file edits, tool
    uses — across any harness, not just the final text. Mirrors the oneharness
    action-event shape; `input` is the structured, tool-shaped args so a consumer
    can match on the command string or file path without re-parsing.

    `input` is a free-form JSON value, so `Message`/`Transcript` are `PartialEq`
    but not `Eq`.
    """

    index: int | None = Field(
        0,
        description='Position within the turn, so ordering ("did X before Y") is expressible.',
        ge=0,
    )
    input: Any | None = Field(
        None,
        description="Structured tool arguments (the command, the file path); `null` when none.",
    )
    kind: str = Field(
        ...,
        description="`tool_call` (the skill invoked a tool) or `tool_result` (the observation).",
    )
    name: str | None = Field(
        None,
        description="Normalized tool name where knowable (e.g. `bash`, `edit_file`); `null` for\na `tool_result` or when the harness did not name it.",
    )
    output: str | None = Field(
        None, description="The result/observation text, when the transcript exposed it."
    )


class Usage(BaseModel):
    """
    Token / cost usage for one provider call.

    Each field is independently optional because not every harness reports every
    signal (cost is commonly absent on subscription auth; some harnesses report
    no usage at all). The whole struct is `Option<Usage>` on a turn — `None`
    means "no signal," not "zero."
    """

    cost_usd: float | None = None
    input_tokens: int | None = Field(None, ge=0)
    output_tokens: int | None = Field(None, ge=0)


class Message(BaseModel):
    """
    A single turn in the conversation.
    """

    content: str
    events: list[ToolEvent] | None = Field(
        None,
        description="The normalized tool events the skill took producing this turn (assistant\nturns only, and only when the harness exposed a tool transcript via\noneharness `--events`). Empty otherwise. Surfaced for post-hoc analysis\nand streamed live for short-circuiting.",
    )
    role: Literal["user", "assistant", "system"] = Field(..., description="Who produced a message.")


class Summary(BaseModel):
    """
    Aggregate pass/fail counts for a report.
    """

    cases: int = Field(..., description="Distinct test cases represented.", ge=0)
    failed: int = Field(..., description="Runs that failed.", ge=0)
    passed: int = Field(..., description="Runs that passed.", ge=0)
    runs: int = Field(..., description="Total (case × platform × model) runs.", ge=0)
    usage: Usage | None = Field(
        None,
        description="Aggregated token/cost usage across every run in the report. Omitted\nwhen no run reported usage.",
    )


class Transcript(BaseModel):
    """
    An ordered list of messages. Thin wrapper so the type reads clearly at call
    sites and so we can grow conversation-level helpers without churn.
    """

    messages: list[Message]


class CaseRun(BaseModel):
    """
    The result of running one test case on one (platform, model) pair.
    """

    case: str = Field(..., description="The test case name.")
    evals: list[EvalOutcome] = Field(..., description="Per-eval outcomes, in declaration order.")
    history_command: str | None = Field(
        None,
        description="A ready-to-run command that replays this run's recorded transcript — e.g.\n`oneharness history show <name> --history-dir <dir>` — so a past run can\nbe reviewed after the fact. Present only when the run was recorded (the\noneharness provider with history enabled); `null` for providers/configs\nthat record no history.",
    )
    mock_calls: list[MockCall] | None = Field(
        None,
        description='Every tool call the mock/spy channel observed, in order, with the\noriginal (pre-rewrite) input and the verdict applied. `null` when the\nchannel was off for this run (no `mocks`, no `spy`); an empty array\nmeans the channel was on and the skill made no tool calls — SDKs use\nthat distinction so a spy on a channel-less run errs instead of reading\nas "zero calls".',
    )
    model: str = Field(..., description="The model this run used.")
    passed: bool = Field(..., description="True iff every eval in this run passed.")
    platform: str = Field(..., description="The harness platform this run used.")
    skill: str = Field(..., description="Absolute-ish path to the skill that was exercised.")
    transcript: Transcript = Field(
        ..., description="The full conversation, for debugging and deterministic mix-in checks."
    )
    turns: int = Field(..., description="Number of assistant turns produced.", ge=0)
    usage: Usage | None = Field(
        None,
        description="Aggregated token/cost usage across every provider call in this run\n(skill turns + simulated-user turns + judge calls). Omitted when no\nusage was reported (e.g. the fake provider or a harness that doesn't\nsurface usage).",
    )


class Report(BaseModel):
    """
    The top-level report for a `skilltest run` invocation.
    """

    passed: bool = Field(..., description="True iff every run passed.")
    runs: list[CaseRun] = Field(..., description="Every individual run.")
    summary: Summary = Field(..., description="Aggregate counts.")
