# generated by datamodel-codegen:
#   filename:  validation.schema.json

from __future__ import annotations
from pydantic import BaseModel, Field


class ValidationFinding(BaseModel):
    """
    One problem found while validating a skill, as serialized in the
    `skilltest validate --format json` output.
    """

    message: str = Field(..., description="What is wrong and how to fix it.")
    skill: str = Field(..., description="The skill directory the finding is about.")


class ValidationReport(BaseModel):
    """
    The top-level report for a `skilltest validate` invocation.
    """

    findings: list[ValidationFinding] = Field(..., description="Every finding, in discovery order.")
    valid: bool = Field(..., description="True iff no findings were produced.")
